apiVersion: v1
kind: Service
metadata:
  namespace: ctse
  name: product-management-service
spec:
  selector:
    app: product-management
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
  type: LoadBalancer
  publishNotReadyAddresses: true
